-- DB/00_reset_database.sql
-- Drop all tables in correct dependency order (PostgreSQL)

-- First drop tables that have foreign keys to other tables
DROP TABLE IF EXISTS MessageReadStatus CASCADE;
DROP TABLE IF EXISTS Messages CASCADE;
DROP TABLE IF EXISTS ConversationParticipants CASCADE;
DROP TABLE IF EXISTS Conversations CASCADE;
DROP TABLE IF EXISTS Vote CASCADE;
DROP TABLE IF EXISTS Comment CASCADE;
DROP TABLE IF EXISTS PostMedia CASCADE;
DROP TABLE IF EXISTS PostViews CASCADE;
DROP TABLE IF EXISTS Post CASCADE;
DROP TABLE IF EXISTS GroupJoinRequests CASCADE;
DROP TABLE IF EXISTS GroupMember CASCADE;
DROP TABLE IF EXISTS GroupSettings CASCADE;
DROP TABLE IF EXISTS Channel CASCADE;
DROP TABLE IF EXISTS MediaFile CASCADE;
DROP TABLE IF EXISTS BinMedia CASCADE;
DROP TABLE IF EXISTS Bin CASCADE;
DROP TABLE IF EXISTS Friends CASCADE;
DROP TABLE IF EXISTS BlockedUsers CASCADE;
DROP TABLE IF EXISTS UserSettings CASCADE;
DROP TABLE IF EXISTS Notifications CASCADE;
DROP TABLE IF EXISTS Reports CASCADE;
DROP TABLE IF EXISTS AdminActions CASCADE;

-- Finally drop base tables
DROP TABLE IF EXISTS GroupsTable CASCADE;
DROP TABLE IF EXISTS Users CASCADE;

-- Drop functions and triggers
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;
DROP FUNCTION IF EXISTS update_vote_counts() CASCADE;
DROP FUNCTION IF EXISTS update_comment_count() CASCADE;
DROP FUNCTION IF EXISTS update_member_count() CASCADE;